"""
Generated by generator/generator.py - 2021-08-09 10:27:19.167654
"""
import pytest


@pytest.fixture()
def media_fixture_response():
    return {
        "Flags": 2097176,
        "QueueType": "NONE",
        "ID": "00000000000000000000000000000000",
        "PersistentID": "000000000-0000-0000-0000-000000000000",
        "Title": "Spotify",
        "DisplayInfo": ["Spotify"],
        "ArtworkRatio": 0,
        "SearchPlaceholderText": "Search for Songs, Albums and Artists",
        "StartIndex": 0,
        "TotalAvailable": 3,
        "MediaItems": [
            {
                "Flags": 1081368,
                "QueueType": "NONE",
                "ID": "00000000000000000000000000000000",
                "PersistentID": "spotify5:instance:00000000-0000-0000-0000-000000000000",
                "GroupName": "Internet Music",
                "Title": "Spotify Browser",
                "Type": 32768,
                "ArtworkURI": "00000000-0000-0000-0000-000000000000",
                "ArtworkRatio": 0,
                "Duration": 0,
                "BitRate": 0,
                "ListenerCount": 0,
                "Rating": 0,
                "TotalItems": -1,
                "DisplayInfo": ["Spotify Browser"],
                "ContextMenuItems": [],
            }
        ],
    }
