"""
Generated by generator/generator.py - 2021-08-03 20:16:46.206915
"""
import pytest


@pytest.fixture()
def nowplaying_fixture_response():
    return {
        "SourceID": 1,
        "QueueCount": 1,
        "QueueSongIndex": 0,
        "ChangeQueueID": 14110,
        "ChangeMetaDataID": 269,
        "ChangeBookmarkID": 10862,
        "BookmarkScope": {
            "ID": "00000000000000000000000000000000",
            "PersistentID": "spotify5:playlist:000000-000000-000000",
            "Title": "Chill",
            "Flags": 545271848,
        },
        "Status": 2,
        "Controls": 318768127,
        "RepeatMode": 0,
        "ShuffleMode": False,
        "CurrSong": {
            "Flags": 4098,
            "QueueType": "spotify:0000000000000000000000000",
            "ID": "00000000000000000000000000000000",
            "PersistentID": "spotcon:session:0000000000000000000000000",
            "Title": "I Didn't Know the Time",
            "Type": 0,
            "ArtworkURI": "https://i.scdn.co/image/ab67616d0000b273b9ad73db3d2b1e6e7f66315a",
            "ArtworkRatio": 0,
            "Album": "Perdida",
            "Artists": "Stone Temple Pilots",
            "Duration": 331.866,
            "DeepLinks": [
                {
                    "Kind": "Album",
                    "Title": "Perdida",
                    "Uri": "spotify:album:0000000000000000000000",
                    "MediaId": "00000000000000000000000000000000",
                }
            ],
            "BitRate": 0,
            "ListenerCount": 0,
            "Rating": 0,
            "TotalItems": 0,
            "DisplayInfo": ["I Didn't Know the Time", "Stone Temple Pilots", "Perdida"],
            "ContextMenuItems": [
                {
                    "Type": 1,
                    "Key": "GoToAlbum",
                    "Title": "Go to Album",
                    "Value": "00000000000000000000000000000000",
                }
            ],
            "AccountName": "Spotify Browser",
        },
        "NextSong": {
            "Flags": 4098,
            "QueueType": "spotify:dhj7ielazg6zbseqmzwj8iilc",
            "ID": "000000000000000000000000000000000",
            "PersistentID": "spotcon:session:00000000000000000000000000000",
            "Title": "Summer Years",
            "Type": 0,
            "ArtworkURI": "https://i.scdn.co/image/ab67616d0000b27397bf91e5ecee3470d063614f",
            "ArtworkRatio": 0,
            "Album": "Thank You for Today",
            "Artists": "Death Cab for Cutie",
            "Duration": 268.16,
            "DeepLinks": [
                {
                    "Kind": "Album",
                    "Title": "Thank You for Today",
                    "Uri": "spotify:album:0000000000000000000000",
                    "MediaId": "00000000000000000000000000000000",
                }
            ],
            "BitRate": 0,
            "ListenerCount": 0,
            "Rating": 0,
            "TotalItems": 0,
            "DisplayInfo": ["Spotify", "Summer Years"],
            "ContextMenuItems": [
                {
                    "Type": 1,
                    "Key": "GoToAlbum",
                    "Title": "Go to Album",
                    "Value": "00000000000000000000000000000000",
                }
            ],
        },
        "CurrProgress": 300,
        "SearchPromptText": "Search for music by artist, album, or title",
        "SourceLockedByZoneID": -1,
        "ServiceName": "Spotify",
        "ServiceID": "00000000-0000-0000-0000-000000000000",
        "ServiceLogoURI": "00000000-0000-0000-0000-000000000000",
    }
