"""
Generated by generator/generator.py - 2021-08-03 20:35:05.287334
"""
import pytest


@pytest.fixture()
def source_fixture_response():
    return {
        "Hidden": False,
        "IsShared": False,
        "Name": "Chill",
        "MediaTypesSupported": 33024,
        "Type": 1,
        "SourceType": 6,
        "SourceID": 0,
        "ExternalDeviceType": 0,
    }
