"""
Generated by generator/generator.py - 2021-07-31 12:29:43.406741
"""
import pytest


@pytest.fixture()
def system_fixture_response():
    return {
        "AppName": "CasaTunes",
        "ControllerFeatures": -1073622790,
        "EQSettings": {"Minimum": -15, "Maximum": 15, "Increment": 1},
        "VolumeSettings": {"Minimum": 0, "Maximum": 100, "Increment": 1},
        "MACAddress": "0000000000000",
        "TeamViewerMACAddress": "0000000000000",
        "IPAddress": "000.000.000.000",
        "CasaTunesVersion": "5.00.210726",
        "WebServicesVersion": "5.6",
        "RESTServicesVersion": "1.40",
        "IsLicenseValid": True,
        "IsCAMSupported": 2,
        "IsAirableLicensed": False,
        "IsSystemSleepEnabled": False,
        "IsPasswordRequired": False,
        "StreamerModeEnabled": False,
        "IsSettingsPasswordRequired": False,
        "IsPrayersEnabled": True,
        "IndexerPort": 20321,
        "MatrixInfo": [
            {
                "Title": "Matrix: CasaTunes CT",
                "Values": [{"Name": "Zones:", "Value": "1-3", "IsError": False}],
            }
        ],
    }
