"""
Generated by generator/generator.py - 2021-07-29 23:36:53.998174
"""
import pytest


@pytest.fixture()
def zone_fixture_response():
    return {
        "Balance": 0,
        "Bass": 0,
        "DND": False,
        "Shared": False,
        "FixedVolume": 0,
        "FixedVolumeEnabled": False,
        "Hidden": False,
        "KeypadLock": False,
        "Loudness": False,
        "LowPassFilterEnabled": False,
        "LowPassFilterSupported": False,
        "LowPassFilter": 0,
        "MasterMode": False,
        "Mute": False,
        "Name": "New Room Group",
        "PartyMode": False,
        "Power": True,
        "MaxVolume": 100,
        "VolumeControlType": 1,
        "ZoneGroupInfo": {
            "zoneId": 1,
            "master": False,
            "keypadLock": False,
            "volumeAdjustment": 0,
            "powerOnVolumeAdjustment": 0,
        },
        "GroupName": "New Room Group",
        "SleepEnabled": False,
        "SourceID": 1,
        "Treble": 0,
        "Volume": 28,
        "WakeupEventSchedule": False,
        "WakeupScheduled": False,
        "ZoneID": 1002,
        "EnabledSources": 7,
        "EnableMuteOrPage": 0,
        "PageVolume": 28,
        "PowerOnVolume": 50,
        "ResetPowerOnVolume": False,
        "PersistentZoneID": "badb017b-52d5-4c8d-92d6-b63e3541d467",
        "ZoneImageID": "",
        "EqType": 0,
        "HidePowerControl": False,
        "HideSourceControl": False,
        "HideDNDControl": False,
        "ZoneNameReadOnly": False,
    }
