"""
Generated by generator/generator.py - 2021-08-03 20:16:46.206915
"""
from pycasatunes.objects.nowplaying import CasaTunesNowPlaying
from tests.responses.nowplaying_fixture import nowplaying_fixture_response


def test_nowplaying(nowplaying_fixture_response):
    obj = CasaTunesNowPlaying(None, nowplaying_fixture_response)
    assert obj.SourceID == nowplaying_fixture_response["SourceID"]
    assert obj.QueueCount == nowplaying_fixture_response["QueueCount"]
    assert obj.QueueSongIndex == nowplaying_fixture_response["QueueSongIndex"]
    assert obj.ChangeQueueID == nowplaying_fixture_response["ChangeQueueID"]
    assert obj.ChangeMetaDataID == nowplaying_fixture_response["ChangeMetaDataID"]
    assert obj.ChangeBookmarkID == nowplaying_fixture_response["ChangeBookmarkID"]
    assert obj.BookmarkScope.ID == nowplaying_fixture_response["BookmarkScope"]["ID"]
    assert (
        obj.BookmarkScope.PersistentID
        == nowplaying_fixture_response["BookmarkScope"]["PersistentID"]
    )
    assert (
        obj.BookmarkScope.Title == nowplaying_fixture_response["BookmarkScope"]["Title"]
    )
    assert (
        obj.BookmarkScope.Flags == nowplaying_fixture_response["BookmarkScope"]["Flags"]
    )
    assert obj.Status == nowplaying_fixture_response["Status"]
    assert obj.Controls == nowplaying_fixture_response["Controls"]
    assert obj.RepeatMode == nowplaying_fixture_response["RepeatMode"]
    assert obj.ShuffleMode == nowplaying_fixture_response["ShuffleMode"]
    assert obj.CurrSong.Flags == nowplaying_fixture_response["CurrSong"]["Flags"]
    assert (
        obj.CurrSong.QueueType == nowplaying_fixture_response["CurrSong"]["QueueType"]
    )
    assert obj.CurrSong.ID == nowplaying_fixture_response["CurrSong"]["ID"]
    assert (
        obj.CurrSong.PersistentID
        == nowplaying_fixture_response["CurrSong"]["PersistentID"]
    )
    assert obj.CurrSong.Title == nowplaying_fixture_response["CurrSong"]["Title"]
    assert obj.CurrSong.Type == nowplaying_fixture_response["CurrSong"]["Type"]
    assert (
        obj.CurrSong.ArtworkURI == nowplaying_fixture_response["CurrSong"]["ArtworkURI"]
    )
    assert (
        obj.CurrSong.ArtworkRatio
        == nowplaying_fixture_response["CurrSong"]["ArtworkRatio"]
    )
    assert obj.CurrSong.Album == nowplaying_fixture_response["CurrSong"]["Album"]
    assert obj.CurrSong.Artists == nowplaying_fixture_response["CurrSong"]["Artists"]
    assert obj.CurrSong.Duration == nowplaying_fixture_response["CurrSong"]["Duration"]
    assert (
        obj.CurrSong.DeepLinks[0].Kind
        == nowplaying_fixture_response["CurrSong"]["DeepLinks"][0]["Kind"]
    )
    assert (
        obj.CurrSong.DeepLinks[0].Title
        == nowplaying_fixture_response["CurrSong"]["DeepLinks"][0]["Title"]
    )
    assert (
        obj.CurrSong.DeepLinks[0].Uri
        == nowplaying_fixture_response["CurrSong"]["DeepLinks"][0]["Uri"]
    )
    assert (
        obj.CurrSong.DeepLinks[0].MediaId
        == nowplaying_fixture_response["CurrSong"]["DeepLinks"][0]["MediaId"]
    )
    assert obj.CurrSong.BitRate == nowplaying_fixture_response["CurrSong"]["BitRate"]
    assert (
        obj.CurrSong.ListenerCount
        == nowplaying_fixture_response["CurrSong"]["ListenerCount"]
    )
    assert obj.CurrSong.Rating == nowplaying_fixture_response["CurrSong"]["Rating"]
    assert (
        obj.CurrSong.TotalItems == nowplaying_fixture_response["CurrSong"]["TotalItems"]
    )
    assert (
        obj.CurrSong.DisplayInfo[0]
        == nowplaying_fixture_response["CurrSong"]["DisplayInfo"][0]
    )
    assert (
        obj.CurrSong.ContextMenuItems[0].Type
        == nowplaying_fixture_response["CurrSong"]["ContextMenuItems"][0]["Type"]
    )
    assert (
        obj.CurrSong.ContextMenuItems[0].Key
        == nowplaying_fixture_response["CurrSong"]["ContextMenuItems"][0]["Key"]
    )
    assert (
        obj.CurrSong.ContextMenuItems[0].Title
        == nowplaying_fixture_response["CurrSong"]["ContextMenuItems"][0]["Title"]
    )
    assert (
        obj.CurrSong.ContextMenuItems[0].Value
        == nowplaying_fixture_response["CurrSong"]["ContextMenuItems"][0]["Value"]
    )
    assert (
        obj.CurrSong.AccountName
        == nowplaying_fixture_response["CurrSong"]["AccountName"]
    )
    assert obj.NextSong.Flags == nowplaying_fixture_response["NextSong"]["Flags"]
    assert (
        obj.NextSong.QueueType == nowplaying_fixture_response["NextSong"]["QueueType"]
    )
    assert obj.NextSong.ID == nowplaying_fixture_response["NextSong"]["ID"]
    assert (
        obj.NextSong.PersistentID
        == nowplaying_fixture_response["NextSong"]["PersistentID"]
    )
    assert obj.NextSong.Title == nowplaying_fixture_response["NextSong"]["Title"]
    assert obj.NextSong.Type == nowplaying_fixture_response["NextSong"]["Type"]
    assert (
        obj.NextSong.ArtworkURI == nowplaying_fixture_response["NextSong"]["ArtworkURI"]
    )
    assert (
        obj.NextSong.ArtworkRatio
        == nowplaying_fixture_response["NextSong"]["ArtworkRatio"]
    )
    assert obj.NextSong.Album == nowplaying_fixture_response["NextSong"]["Album"]
    assert obj.NextSong.Artists == nowplaying_fixture_response["NextSong"]["Artists"]
    assert obj.NextSong.Duration == nowplaying_fixture_response["NextSong"]["Duration"]
    assert (
        obj.NextSong.DeepLinks[0].Kind
        == nowplaying_fixture_response["NextSong"]["DeepLinks"][0]["Kind"]
    )
    assert (
        obj.NextSong.DeepLinks[0].Title
        == nowplaying_fixture_response["NextSong"]["DeepLinks"][0]["Title"]
    )
    assert (
        obj.NextSong.DeepLinks[0].Uri
        == nowplaying_fixture_response["NextSong"]["DeepLinks"][0]["Uri"]
    )
    assert (
        obj.NextSong.DeepLinks[0].MediaId
        == nowplaying_fixture_response["NextSong"]["DeepLinks"][0]["MediaId"]
    )
    assert obj.NextSong.BitRate == nowplaying_fixture_response["NextSong"]["BitRate"]
    assert (
        obj.NextSong.ListenerCount
        == nowplaying_fixture_response["NextSong"]["ListenerCount"]
    )
    assert obj.NextSong.Rating == nowplaying_fixture_response["NextSong"]["Rating"]
    assert (
        obj.NextSong.TotalItems == nowplaying_fixture_response["NextSong"]["TotalItems"]
    )
    assert (
        obj.NextSong.DisplayInfo[0]
        == nowplaying_fixture_response["NextSong"]["DisplayInfo"][0]
    )
    assert (
        obj.NextSong.ContextMenuItems[0].Type
        == nowplaying_fixture_response["NextSong"]["ContextMenuItems"][0]["Type"]
    )
    assert (
        obj.NextSong.ContextMenuItems[0].Key
        == nowplaying_fixture_response["NextSong"]["ContextMenuItems"][0]["Key"]
    )
    assert (
        obj.NextSong.ContextMenuItems[0].Title
        == nowplaying_fixture_response["NextSong"]["ContextMenuItems"][0]["Title"]
    )
    assert (
        obj.NextSong.ContextMenuItems[0].Value
        == nowplaying_fixture_response["NextSong"]["ContextMenuItems"][0]["Value"]
    )
    assert obj.CurrProgress == nowplaying_fixture_response["CurrProgress"]
    assert obj.SearchPromptText == nowplaying_fixture_response["SearchPromptText"]
    assert (
        obj.SourceLockedByZoneID == nowplaying_fixture_response["SourceLockedByZoneID"]
    )
    assert obj.ServiceName == nowplaying_fixture_response["ServiceName"]
    assert obj.ServiceID == nowplaying_fixture_response["ServiceID"]
    assert obj.ServiceLogoURI == nowplaying_fixture_response["ServiceLogoURI"]
