"""
Generated by generator/generator.py - 2021-08-09 10:27:19.167654
"""
from pycasatunes.objects.media import CasaTunesMedia
from tests.responses.media_fixture import media_fixture_response


def test_media(media_fixture_response):
    obj = CasaTunesMedia(None, media_fixture_response)
    assert obj.Flags == media_fixture_response["Flags"]
    assert obj.QueueType == media_fixture_response["QueueType"]
    assert obj.ID == media_fixture_response["ID"]
    assert obj.PersistentID == media_fixture_response["PersistentID"]
    assert obj.Title == media_fixture_response["Title"]
    assert obj.DisplayInfo[0] == media_fixture_response["DisplayInfo"][0]
    assert obj.ArtworkRatio == media_fixture_response["ArtworkRatio"]
    assert obj.SearchPlaceholderText == media_fixture_response["SearchPlaceholderText"]
    assert obj.StartIndex == media_fixture_response["StartIndex"]
    assert obj.TotalAvailable == media_fixture_response["TotalAvailable"]
    assert obj.MediaItems[0].Flags == media_fixture_response["MediaItems"][0]["Flags"]
    assert (
        obj.MediaItems[0].QueueType
        == media_fixture_response["MediaItems"][0]["QueueType"]
    )
    assert obj.MediaItems[0].ID == media_fixture_response["MediaItems"][0]["ID"]
    assert (
        obj.MediaItems[0].PersistentID
        == media_fixture_response["MediaItems"][0]["PersistentID"]
    )
    assert (
        obj.MediaItems[0].GroupName
        == media_fixture_response["MediaItems"][0]["GroupName"]
    )
    assert obj.MediaItems[0].Title == media_fixture_response["MediaItems"][0]["Title"]
    assert obj.MediaItems[0].Type == media_fixture_response["MediaItems"][0]["Type"]
    assert (
        obj.MediaItems[0].ArtworkURI
        == media_fixture_response["MediaItems"][0]["ArtworkURI"]
    )
    assert (
        obj.MediaItems[0].ArtworkRatio
        == media_fixture_response["MediaItems"][0]["ArtworkRatio"]
    )
    assert (
        obj.MediaItems[0].Duration
        == media_fixture_response["MediaItems"][0]["Duration"]
    )
    assert (
        obj.MediaItems[0].BitRate == media_fixture_response["MediaItems"][0]["BitRate"]
    )
    assert (
        obj.MediaItems[0].ListenerCount
        == media_fixture_response["MediaItems"][0]["ListenerCount"]
    )
    assert obj.MediaItems[0].Rating == media_fixture_response["MediaItems"][0]["Rating"]
    assert (
        obj.MediaItems[0].TotalItems
        == media_fixture_response["MediaItems"][0]["TotalItems"]
    )
    assert (
        obj.MediaItems[0].DisplayInfo
        == media_fixture_response["MediaItems"][0]["DisplayInfo"]
    )
    assert (
        obj.MediaItems[0].ContextMenuItems
        == media_fixture_response["MediaItems"][0]["ContextMenuItems"]
    )
