"""
Generated by generator/generator.py - 2021-08-03 20:35:05.287334
"""
from pycasatunes.objects.source import CasaTunesSource
from tests.responses.source_fixture import source_fixture_response


def test_source(source_fixture_response):
    obj = CasaTunesSource(source_fixture_response)
    assert obj.Hidden == source_fixture_response["Hidden"]
    assert obj.IsShared == source_fixture_response["IsShared"]
    assert obj.Name == source_fixture_response["Name"]
    assert obj.MediaTypesSupported == source_fixture_response["MediaTypesSupported"]
    assert obj.Type == source_fixture_response["Type"]
    assert obj.SourceType == source_fixture_response["SourceType"]
    assert obj.SourceID == source_fixture_response["SourceID"]
    assert obj.ExternalDeviceType == source_fixture_response["ExternalDeviceType"]
