"""
Generated by generator/generator.py - 2021-07-29 23:36:53.998174
"""
from pycasatunes.objects.zone import CasaTunesZone
from tests.responses.zone_fixture import zone_fixture_response


def test_zone(zone_fixture_response):
    obj = CasaTunesZone(None, zone_fixture_response)
    assert obj.Balance == zone_fixture_response["Balance"]
    assert obj.Bass == zone_fixture_response["Bass"]
    assert obj.DND == zone_fixture_response["DND"]
    assert obj.Shared == zone_fixture_response["Shared"]
    assert obj.FixedVolume == zone_fixture_response["FixedVolume"]
    assert obj.FixedVolumeEnabled == zone_fixture_response["FixedVolumeEnabled"]
    assert obj.Hidden == zone_fixture_response["Hidden"]
    assert obj.KeypadLock == zone_fixture_response["KeypadLock"]
    assert obj.Loudness == zone_fixture_response["Loudness"]
    assert obj.LowPassFilterEnabled == zone_fixture_response["LowPassFilterEnabled"]
    assert obj.LowPassFilterSupported == zone_fixture_response["LowPassFilterSupported"]
    assert obj.LowPassFilter == zone_fixture_response["LowPassFilter"]
    assert obj.MasterMode == zone_fixture_response["MasterMode"]
    assert obj.Mute == zone_fixture_response["Mute"]
    assert obj.Name == zone_fixture_response["Name"]
    assert obj.PartyMode == zone_fixture_response["PartyMode"]
    assert obj.Power == zone_fixture_response["Power"]
    assert obj.MaxVolume == zone_fixture_response["MaxVolume"]
    assert obj.VolumeControlType == zone_fixture_response["VolumeControlType"]
    assert obj.ZoneGroupInfo.zoneId == zone_fixture_response["ZoneGroupInfo"]["zoneId"]
    assert obj.ZoneGroupInfo.master == zone_fixture_response["ZoneGroupInfo"]["master"]
    assert (
        obj.ZoneGroupInfo.keypadLock
        == zone_fixture_response["ZoneGroupInfo"]["keypadLock"]
    )
    assert (
        obj.ZoneGroupInfo.volumeAdjustment
        == zone_fixture_response["ZoneGroupInfo"]["volumeAdjustment"]
    )
    assert (
        obj.ZoneGroupInfo.powerOnVolumeAdjustment
        == zone_fixture_response["ZoneGroupInfo"]["powerOnVolumeAdjustment"]
    )
    assert obj.GroupName == zone_fixture_response["GroupName"]
    assert obj.SleepEnabled == zone_fixture_response["SleepEnabled"]
    assert obj.SourceID == zone_fixture_response["SourceID"]
    assert obj.Treble == zone_fixture_response["Treble"]
    assert obj.Volume == zone_fixture_response["Volume"]
    assert obj.WakeupEventSchedule == zone_fixture_response["WakeupEventSchedule"]
    assert obj.WakeupScheduled == zone_fixture_response["WakeupScheduled"]
    assert obj.ZoneID == zone_fixture_response["ZoneID"]
    assert obj.EnabledSources == zone_fixture_response["EnabledSources"]
    assert obj.EnableMuteOrPage == zone_fixture_response["EnableMuteOrPage"]
    assert obj.PageVolume == zone_fixture_response["PageVolume"]
    assert obj.PowerOnVolume == zone_fixture_response["PowerOnVolume"]
    assert obj.ResetPowerOnVolume == zone_fixture_response["ResetPowerOnVolume"]
    assert obj.PersistentZoneID == zone_fixture_response["PersistentZoneID"]
    assert obj.ZoneImageID == zone_fixture_response["ZoneImageID"]
    assert obj.EqType == zone_fixture_response["EqType"]
    assert obj.HidePowerControl == zone_fixture_response["HidePowerControl"]
    assert obj.HideSourceControl == zone_fixture_response["HideSourceControl"]
    assert obj.HideDNDControl == zone_fixture_response["HideDNDControl"]
    assert obj.ZoneNameReadOnly == zone_fixture_response["ZoneNameReadOnly"]
